#!/bin/bash

# Copy BUILD_NAME/SDK specific binary blobs from new GPL to development repo

#
# Usage: enter the new GPL directory then run this script.
#        Then run by specifying the BUILD_NAME number as argument.
#        REPO will contain the location of your local repository

BUILD_NAME=$(echo $1 | tr "[:lower:]" "[:upper:]")
BUILD_NAME_LC=$(echo $BUILD_NAME | tr "[:upper:]" "[:lower:]")
REPO=/home/paldier/release/asuswrt-bcm
#REPO=/home/paldier/release/swrt-bcm

echo "*** Copying platform-specific files..."
if [ "$BUILD_NAME" == "RT-AC88U" ] || [ "$BUILD_NAME" == "RT-AC3100" ] || [ "$BUILD_NAME" == "RT-AC5300" ]
then
	SDK="_7114"
	ARCH="_arm"
	HND=""

	cp -f release/src/router/ctf_arm/bcm_7114_gmac3/* $REPO/release/src/router/ctf_arm/bcm_7114_gmac3/
	cp -f release/src/router/wl_arm_7114/prebuilt/* $REPO/release/src/router/wl_arm_7114/prebuilt/$BUILD_NAME/
	cp -f release/src/router/envram_bin/envram$ARCH$SDK/* $REPO/release/src/router/envram_bin/envram$ARCH$SDK/
	cp -f release/src-rt-7.14.114.x/src/wl/exe/prebuilt/* $REPO/release/src-rt-7.14.114.x/src/wl/exe/prebuilt/$BUILD_NAME/

elif [ "$BUILD_NAME" == "RT-AC68U" ]
then
	SDK=""
	ARCH="_arm"
	HND=""

	cp -f release/src/router/ctf_arm/bcm6/* $REPO/release/src/router/ctf_arm/bcm6/
	cp -f release/src/router/wl_arm/prebuilt/* $REPO/release/src/router/wl_arm/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-6.x.4708/wl/exe/prebuilt/* $REPO/release/src-rt-6.x.4708/wl/exe/prebuilt/
	cp -a release/src/router/tuxera/broadcom$ARCH$SDK/* $REPO/release/src/router/tuxera/broadcom$ARCH$SDK/

elif [ "$BUILD_NAME" == "RT-AC86U" ] || [ "$BUILD_NAME" == "GT-AC2900" ] || [ "$BUILD_NAME" == "GT-AC5300" ]
then
	SDK="_94908hnd"
	ARCH="_arm"
	HND="_hnd"

	rsync -a --del release/src/router/hnd_extra/prebuilt/ $REPO/release/src/router/hnd_extra/prebuilt/$BUILD_NAME
	if [ "$BUILD_NAME" == "RT-AC86U" ]
	then
		ln -s ../GT-AC2900/vis-dcon $REPO/release/src/router/hnd_extra/prebuilt/RT-AC86U/vis-dcon
		ln -s ../GT-AC2900/vis-datacollector $REPO/release/src/router/hnd_extra/prebuilt/RT-AC86U/vis-datacollector
	elif [ "$BUILD_NAME" == "GT-AC5300" ]
	then
		ln -s ../GT-AC2900/vis-dcon $REPO/release/src/router/hnd_extra/prebuilt/GT-AC5300/vis-dcon
		ln -s ../GT-AC2900/vis-datacollector $REPO/release/src/router/hnd_extra/prebuilt/GT-AC5300/vis-datacollector
	fi
	cp -f release/src/router/envram_bin/envram${ARCH}${SDK}/* $REPO/release/src/router/envram_bin/envram${ARCH}${SDK}/
	cp -f release/src-rt-5.02hnd/wl/exe/prebuilt/* $REPO/release/src-rt-5.02hnd/wl/exe/prebuilt/
	cp -f release/src-rt-5.02hnd/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.02hnd/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src/router/rdpactl/prebuilt/* $REPO/release/src/router/rdpactl/prebuilt/
	cp -f release/src/router/pwrctl_lib/prebuilt/* $REPO/release/src/router/pwrctl_lib/prebuilt/
	cp -f release/src/router/bcm_flasher/prebuilt/* $REPO/release/src/router/bcm_flasher/prebuilt/
	cp -f release/src/router/bcmmcastctl/prebuilt/* $REPO/release/src/router/bcmmcastctl/prebuilt/
	cp -f release/src/router/bcmtm_lib/prebuilt/* $REPO/release/src/router/bcmtm_lib/prebuilt/
	cp -f release/src/router/pwrctl/prebuilt/* $REPO/release/src/router/pwrctl/prebuilt/
	cp -f release/src/router/ethswctl/prebuilt/* $REPO/release/src/router/ethswctl/prebuilt/
	cp -f release/src/router/wlcsm/prebuilt/* $REPO/release/src/router/wlcsm/prebuilt/
	cp -f release/src/router/fcctl_lib/prebuilt/* $REPO/release/src/router/fcctl_lib/prebuilt/
	cp -f release/src/router/swmdk/prebuilt/* $REPO/release/src/router/swmdk/prebuilt/
	cp -f release/src/router/vlanctl_lib/prebuilt/* $REPO/release/src/router/vlanctl_lib/prebuilt/
	cp -f release/src/router/mcpctl/prebuilt/* $REPO/release/src/router/mcpctl/prebuilt/
	cp -f release/src/router/dnsspoof/prebuilt/* $REPO/release/src/router/dnsspoof/prebuilt/
	cp -f release/src/router/stlport/prebuilt/* $REPO/release/src/router/stlport/prebuilt/
	cp -f release/src/router/tmctl/prebuilt/* $REPO/release/src/router/tmctl/prebuilt/
	cp -f release/src/router/mdk/prebuilt/* $REPO/release/src/router/mdk/prebuilt/
	cp -f release/src/router/ethctl/prebuilt/* $REPO/release/src/router/ethctl/prebuilt/
	cp -f release/src/router/appeventd/prebuilt/* $REPO/release/src/router/appeventd/prebuilt/
	cp -f release/src/router/bcm_boardctl/prebuilt/* $REPO/release/src/router/bcm_boardctl/prebuilt/
	cp -f release/src/router/mcpd/prebuilt/* $REPO/release/src/router/mcpd/prebuilt/
	cp -f release/src/router/prebuilt/* $REPO/release/src/router/prebuilt/
	cp -f release/src/router/ethswctl_lib/prebuilt/* $REPO/release/src/router/ethswctl_lib/prebuilt/
	cp -f release/src/router/bcmtm/prebuilt/* $REPO/release/src/router/bcmtm/prebuilt/
	cp -f release/src/router/bcm_flashutil/prebuilt/* $REPO/release/src/router/bcm_flashutil/prebuilt/
	cp -f release/src/router/ethctl_lib/prebuilt/* $REPO/release/src/router/ethctl_lib/prebuilt/
	cp -f release/src/router/bcm_boot_launcher/prebuilt/* $REPO/release/src/router/bcm_boot_launcher/prebuilt/
	cp -f release/src/router/bpmctl/prebuilt/* $REPO/release/src/router/bpmctl/prebuilt/
	cp -f release/src/router/vpmstats/prebuilt/* $REPO/release/src/router/vpmstats/prebuilt/
	cp -f release/src/router/wlan/util/prebuilt/* $REPO/release/src/router/wlan/util/prebuilt/
	cp -f release/src/router/wlan/nvram/prebuilt/* $REPO/release/src/router/wlan/nvram/prebuilt/
	cp -f release/src/router/bcmmcast/prebuilt/* $REPO/release/src/router/bcmmcast/prebuilt/
	cp -f release/src/router/vlanctl/prebuilt/* $REPO/release/src/router/vlanctl/prebuilt/
	cp -f release/src/router/fcctl/prebuilt/* $REPO/release/src/router/fcctl/prebuilt/
	cp -f release/src/router/tmctl_lib/prebuilt/* $REPO/release/src/router/tmctl_lib/prebuilt/
	cp -f release/src/router/bridgeutil/prebuilt/* $REPO/release/src/router/bridgeutil/prebuilt/

elif [ "$BUILD_NAME" == "RT-AX88U" ] || [ "$BUILD_NAME" == "RT-AX92U" ] || [ "$BUILD_NAME" == "GT-AX11000" ]
then
	SDK="_axhnd"
	ARCH="_arm"
	HND="_axhnd"

	cp -f release/src-rt-5.02axhnd/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.02axhnd/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.02axhnd/wl/exe/prebuilt/* $REPO/release/src-rt-5.02axhnd/wl/exe/prebuilt/
	cp -f release/src-rt-5.02axhnd/hostTools/prebuilt/cmplzma $REPO/release/src-rt-5.02axhnd/hostTools/prebuilt/
	cp -f release/src-rt-5.02axhnd/hostTools/prebuilt/lzmacmd $REPO/release/src-rt-5.02axhnd/hostTools/prebuilt/
	cp -f release/src-rt-5.02axhnd/bcmdrivers/broadcom/net/wl/impl51/main/components/apps/acsdv2/prebuilt/* $REPO/release/src-rt-5.02axhnd/bcmdrivers/broadcom/net/wl/impl51/main/components/apps/acsdv2/prebuilt/$BUILD_NAME/
	rsync -a --del release/src-rt-5.02axhnd/router-sysdep/ $REPO/release/src-rt-5.02axhnd/router-sysdep.$BUILD_NAME_LC

elif [ "$BUILD_NAME" == "RT-AX55" ] || [ "$BUILD_NAME" == "RT-AX56U" ] || [ "$BUILD_NAME" == "RT-AX58U" ] || [ "$BUILD_NAME" == "RT-AX82U" ] || [ "$BUILD_NAME" == "TUF-AX3000" ] || [ "$BUILD_NAME" == "TUF-AX5400" ] || [ "$BUILD_NAME" == "RT-AX95Q" ] || [ "$BUILD_NAME" == "RT-AXE95Q" ]
then
	SDK="_6750hnd"
	ARCH="_arm"
	HND="_6750hnd"

	cp -f release/src-rt-5.02axhnd.675x/wl/exe/prebuilt/* $REPO/release/src-rt-5.02axhnd.675x/wl/exe/prebuilt/
	cp -f release/src-rt-5.02axhnd.675x/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.02axhnd.675x/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.02axhnd.675x/hostTools/prebuilt/cmplzma $REPO/release/src-rt-5.02axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.02axhnd.675x/hostTools/prebuilt/lzmacmd $REPO/release/src-rt-5.02axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.02axhnd.675x/bcmdrivers/broadcom/net/wl/impl69/main/components/apps/acsdv2/prebuilt/* $REPO/release/src-rt-5.02axhnd.675x/bcmdrivers/broadcom/net/wl/impl69/main/components/apps/acsdv2/prebuilt/$BUILD_NAME/
	rsync -a --del release/src-rt-5.02axhnd.675x/router-sysdep/ $REPO/release/src-rt-5.02axhnd.675x/router-sysdep.$BUILD_NAME_LC
elif [ "$BUILD_NAME" == "RT-AX86U" ] || [ "$BUILD_NAME" == "RT-AX68U" ] || [ "$BUILD_NAME" == "RT-AC68U_V4" ] || [ "$BUILD_NAME" == "GT-AXE11000" ]
then
	SDK="_axhnd"
	ARCH="_arm"
	HND="_axhnd"

	cp -f release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/cmplzma $REPO/release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/
	cp -f release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/lzmacmd $REPO/release/src-rt-5.02L.07p2axhnd/hostTools/prebuilt/
	cp -f release/src-rt-5.02L.07p2axhnd/bcmdrivers/broadcom/net/wl/impl69/main/components/apps/acsdv2/prebuilt/* $REPO/release/src-rt-5.02L.07p2axhnd/bcmdrivers/broadcom/net/wl/impl69/main/components/apps/acsdv2/prebuilt/$BUILD_NAME/
	cp -ar release/src-rt-5.02L.07p2axhnd/bcmdrivers/broadcom/net/wl/impl69/sys/src/dongle/sysdeps/default/* $REPO/release/src-rt-5.02L.07p2axhnd/bcmdrivers/broadcom/net/wl/impl69/sys/src/dongle/sysdeps/$BUILD_NAME/
	cp -f release/src-rt-5.02L.07p2axhnd/targets/cfe/prebuilt/* $REPO/release/src-rt-5.02L.07p2axhnd/targets/cfe/sysdeps/$BUILD_NAME/
	rsync -a --del release/src-rt-5.02L.07p2axhnd/router-sysdep/ $REPO/release/src-rt-5.02L.07p2axhnd/router-sysdep.$BUILD_NAME_LC

elif [ "$BUILD_NAME" == "GT-AX6000" ] || [ "$BUILD_NAME" == "XT12" ] || [ "$BUILD_NAME" == "GT-AXE16000" ] || [ "$BUILD_NAME" == "GT-AX11000_PRO" ] || [ "$BUILD_NAME" == "RT-AX86U_PRO" ] || [ "$BUILD_NAME" == "RT-AX88U_PRO" ]
then
        SDK="_4912hnd"
        ARCH="_arm"
        HND="_axhnd"

	rsync -a --del release/src-rt-5.04axhnd.675x/bootloaders/obj/ $REPO/release/src-rt-5.04axhnd.675x/bootloaders/obj.$BUILD_NAME_LC
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/lzop $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/cmplzma $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/lzmacmd $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt//cmplzma $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/mkfs.ubifs $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/mksquashfs $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/ubinize $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/acsdv2/prebuilt/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/acsdv2/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/cevent_app/prebuilt/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/cevent_app/prebuilt/$BUILD_NAME/

	cp -ar release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/sys/src/dongle/sysdeps/default/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/sys/src/dongle/sysdeps/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/archer/impl1/archer.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/bcmlibs/impl1/bcmlibs.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/bpm/impl1/bcm_bpm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/chipinfo/impl1/chipinfo.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/cleds/impl1/bcm_cleds.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/cmdlist/impl1/cmdlist.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/ingqos/impl1/bcm_ingqos.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pktflow/impl1/pktflow.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/mpm/impl1/bcm_mpm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pwrmngtd/impl1/pwrmngtd.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/otp/impl1/otp.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pktrunner/impl2/pktrunner.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/wlcsm_ext/impl1/wlcsm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/vlan/impl1/bcmvlan.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/license/impl1/bcm_license.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/

	echo "Manually sync router-sysdep (since hnd_extra cannot be rsync'ed)"
#	rsync -a --del release/src-rt-5.04axhnd.675x/router-sysdep/ $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC
elif [ "$BUILD_NAME" == "TUF-AX3000_V2" ] || [ "$BUILD_NAME" == "TUF-AX5400_V2" ] || [ "$BUILD_NAME" == "RT-AX82U_V2" ]
then
        SDK="_6756hnd"
        ARCH="_arm"
        HND="_axhnd"

	rsync -a --del release/src-rt-5.04axhnd.675x/bootloaders/obj/ $REPO/release/src-rt-5.04axhnd.675x/bootloaders/obj.$BUILD_NAME_LC
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/addvtoken $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/lzop $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/cmplzma $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/lzmacmd $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt//cmplzma $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/mkfs.ubifs $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/mksquashfs $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/hostTools/prebuilt/ubinize $REPO/release/src-rt-5.04axhnd.675x/hostTools/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/acsdv2/prebuilt/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/acsdv2/prebuilt/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/cevent_app/prebuilt/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/main/components/apps/cevent_app/prebuilt/$BUILD_NAME/

	cp -ar release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/sys/src/dongle/sysdeps/default/* $REPO/release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/net/wl/impl87/sys/src/dongle/sysdeps/$BUILD_NAME/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/archer/impl1/archer.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/bcmlibs/impl1/bcmlibs.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/bpm/impl1/bcm_bpm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/chipinfo/impl1/chipinfo.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/cleds/impl1/bcm_cleds.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/cmdlist/impl1/cmdlist.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/ingqos/impl1/bcm_ingqos.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pktflow/impl1/pktflow.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/mpm/impl1/bcm_mpm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pwrmngtd/impl1/pwrmngtd.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/otp/impl1/otp.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/pktrunner/impl2/pktrunner.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/wlcsm_ext/impl1/wlcsm.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/vlan/impl1/bcmvlan.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	cp -f release/src-rt-5.04axhnd.675x/bcmdrivers/broadcom/char/license/impl1/bcm_license.o $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC/hnd_extra/prebuilt/
	echo "Manually sync router-sysdep (since hnd_extra cannot be rsync'ed)"
#	rsync -a --del release/src-rt-5.04axhnd.675x/router-sysdep/ $REPO/release/src-rt-5.04axhnd.675x/router-sysdep.$BUILD_NAME_LC
else
	echo "Unrecognized BUILD_NAME!"
	exit
fi


# Skip these if no USB port

echo "*** Copying USB-related files..."
if [ "$BUILD_NAME" != "XT12" ] && [ "$BUILD_NAME" != "RT-AX55" ]
then
	cp -ar release/src/router/tuxera/broadcom* $REPO/release/src/router/tuxera/
	cp -f release/src/router/lighttpd-1.4.39/prebuild/* $REPO/release/src/router/lighttpd-1.4.39/prebuild/$BUILD_NAME/
	cp -f release/src/router/dropbox_client/prebuild/* $REPO/release/src/router/dropbox_client/prebuild/$BUILD_NAME/
	cp -f release/src/router/ftpclient/prebuild/* $REPO/release/src/router/ftpclient/prebuild/$BUILD_NAME/
	cp -f release/src/router/sambaclient/prebuild/* $REPO/release/src/router/sambaclient/prebuild/$BUILD_NAME/
	cp -f release/src/router/u2ec/prebuild/* $REPO/release/src/router/u2ec/prebuild/$BUILD_NAME/
	cp -f release/src/router/webdav_client/prebuild/* $REPO/release/src/router/webdav_client/prebuild/$BUILD_NAME/
	cp -f release/src/router/usbclient/prebuild/* $REPO/release/src/router/usbclient/prebuild/$BUILD_NAME/
	cp -f release/src/router/asuswebstorage/prebuild/* $REPO/release/src/router/asuswebstorage/prebuild/$BUILD_NAME/
	cp -f release/src/router/inotify/prebuild/* $REPO/release/src/router/inotify/prebuild/$BUILD_NAME/
fi;

# Common to all

# NOTE: these are new in 388, need to determine which platform uses them
cp -f release/src/router/dns_ping/prebuild/* $REPO/release/src/router/dns_ping/prebuild/$BUILD_NAME
cp -f release/src/router/fsmd/prebuild/* $REPO/release/src/router/fsmd/prebuild/$BUILD_NAME

echo "*** Copying common files..."
cp -f release/src/router/httpd/prebuild/* $REPO/release/src/router/httpd/prebuild/$BUILD_NAME
cp -f release/src/router/rc/prebuild/* $REPO/release/src/router/rc/prebuild/$BUILD_NAME
cp -f release/src/router/shared/prebuild/* $REPO/release/src/router/shared/prebuild/$BUILD_NAME
cp -f release/src/router/sw-hw-auth/prebuild/* $REPO/release/src/router/sw-hw-auth/prebuild/$BUILD_NAME/
cp -f release/src/router/bwdpi_source/asus/prebuild/* $REPO/release/src/router/bwdpi_source/asus/prebuild/$BUILD_NAME/
cp -f release/src/router/bwdpi_source/asus_sql/prebuild/* $REPO/release/src/router/bwdpi_source/asus_sql/prebuild/$BUILD_NAME/
cp -f release/src/router/bwdpi_source/prebuild/* $REPO/release/src/router/bwdpi_source/prebuild/$BUILD_NAME/
cp -f release/src/router/dropbox_client/prebuild/* $REPO/release/src/router/dropbox_client/prebuild/$BUILD_NAME/

cp -f release/src/router/ftpclient/prebuild/* $REPO/release/src/router/ftpclient/prebuild/$BUILD_NAME/
cp -f release/src/router/protect_srv/prebuild/* $REPO/release/src/router/protect_srv/prebuild/$BUILD_NAME/
cp -f release/src/router/protect_srv/lib/prebuild/* $REPO/release/src/router/protect_srv/lib/prebuild/$BUILD_NAME/
cp -f release/src/router/wlc_nt/prebuild/* $REPO/release/src/router/wlc_nt/prebuild/$BUILD_NAME/
cp -f release/src/router/networkmap/prebuild/* $REPO/release/src/router/networkmap/prebuild/$BUILD_NAME/
cp -f release/src/router/nt_center/prebuild/* $REPO/release/src/router/nt_center/prebuild/$BUILD_NAME/
cp -f release/src/router/nt_center/actMail/prebuild/* $REPO/release/src/router/nt_center/actMail/prebuild/$BUILD_NAME/
cp -f release/src/router/nt_center/lib/prebuild/* $REPO/release/src/router/nt_center/lib/prebuild/$BUILD_NAME/
cp -f release/src/router/libletsencrypt/prebuild/* $REPO/release/src/router/libletsencrypt/prebuild/$BUILD_NAME/
cp -f release/src/router/libbcm/prebuilt/* $REPO/release/src/router/libbcm/prebuilt/$BUILD_NAME/
cp -f release/src/router/infosvr/prebuild/* $REPO/release/src/router/infosvr/prebuild/$BUILD_NAME/
cp -ar release/src/router/ookla_speedtest/OOKLA-* $REPO/release/src/router/ookla_speedtest/
cp -f release/src/router/libwebapi/prebuild/* $REPO/release/src/router/libwebapi/prebuild/$BUILD_NAME/
cp -f release/src/router/wlceventd/prebuilt/* $REPO/release/src/router/wlceventd/prebuilt/$BUILD_NAME/
cp -f release/src/router/libvpn/prebuild/* $REPO/release/src/router/libvpn/prebuild/$BUILD_NAME/

# Common to most
echo "*** Copying optional files - ignore errors"
cp -f release/src/router/dblog/daemon/prebuild/* $REPO/release/src/router/dblog/daemon/prebuild/$BUILD_NAME/
cp -f release/src/router/dblog/commands/prebuild/* $REPO/release/src/router/dblog/commands/prebuild/$BUILD_NAME/
cp -f release/src/router/ahs/prebuild/* $REPO/release/src/router/ahs/prebuild/$BUILD_NAME/
cp -f release/src/router/asd/prebuild/* $REPO/release/src/router/asd/prebuild/$BUILD_NAME/
cp -f release/src/router/libasc/prebuild/* $REPO/release/src/router/libasc/prebuild/$BUILD_NAME/
cp -f release/src/router/amas-utils/prebuild/* $REPO/release/src/router/amas-utils/prebuild/$BUILD_NAME/
cp -f release/src/router/cfg_mnt/prebuild/* $REPO/release/src/router/cfg_mnt/prebuild/$BUILD_NAME/
cp -f release/src/router/aaews/prebuild/* $REPO/release/src/router/aaews/prebuild/$BUILD_NAME/
cp -f release/src/router/asusnatnl/natnl/prebuild/* $REPO/release/src/router/asusnatnl/natnl/prebuild/$BUILD_NAME/
cp -f release/src/router/libasuslog/prebuild/* $REPO/release/src/router/libasuslog/prebuild/$BUILD_NAME/
cp -f release/src/router/sysstate/log_daemon/prebuild/* $REPO/release/src/router/sysstate/log_daemon/prebuild/$BUILD_NAME/
cp -f release/src/router/sysstate/commands/prebuild/* $REPO/release/src/router/sysstate/commands/prebuild/$BUILD_NAME/
cp -f release/src/router/wb/prebuild/* $REPO/release/src/router/wb/prebuild/$BUILD_NAME/
cp -f release/src/router/eventd/prebuilt/* $REPO/release/src/router/eventd/prebuilt/$BUILD_NAME/
echo "*** Copying exceptions and special cases..."

# Pre-HND
if [ "$HND" == "" ]
then
	cp -f release/src/router/et$ARCH$SDK/prebuilt/* $REPO/release/src/router/et$ARCH$SDK/prebuilt/
	cp -f release/src/router/emf$ARCH$SDK/*.o $REPO/release/src/router/emf$ARCH$SDK/
	cp -f release/src/router/emf$ARCH$SDK/emfconf/prebuilt/* $REPO/release/src/router/emf$ARCH$SDK/emfconf/prebuilt/
	cp -f release/src/router/emf$ARCH$SDK/igsconf/prebuilt/* $REPO/release/src/router/emf$ARCH$SDK/igsconf/prebuilt/
fi

# On AX these are in router-sysdep
if [ "$HND" == "" ] || [ "$HND" == "_hnd" ]
then
	cp -f release/src/router/acsd$ARCH$SDK/prebuilt/* $REPO/release/src/router/acsd$ARCH$SDK/prebuilt/
	cp -f release/src/router/eapd$ARCH$SDK/linux/prebuilt/* $REPO/release/src/router/eapd$ARCH$SDK/linux/prebuilt/
	cp -a release/src/router/libupnp$ARCH$SDK/* $REPO/release/src/router/libupnp$ARCH$SDK/
	cp -f release/src/router/nas$ARCH$SDK/nas/prebuilt/* $REPO/release/src/router/nas$ARCH$SDK/nas/prebuilt/
	cp -f release/src/router/wlconf$ARCH$SDK/prebuilt/* $REPO/release/src/router/wlconf$ARCH$SDK/prebuilt/
	cp -f release/src/router/wps$ARCH$SDK/prebuilt/* $REPO/release/src/router/wps$ARCH$SDK/prebuilt/
	cp -f release/src/router/wlceventd/prebuilt/* $REPO/release/src/router/wlceventd/prebuilt/$BUILD_NAME/
	cp -f release/src/router/dhd_monitor/prebuilt/* $REPO/release/src/router/dhd_monitor/prebuilt/$BUILD_NAME/
fi

# Model-specific
if [ "$BUILD_NAME" == "RT-AC88U" ]
then
	cp -f release/src/router/rtl_bin/prebuilt/* $REPO/release/src/router/rtl_bin/prebuilt/
fi
if [ "$BUILD_NAME" == "GT-AC2900" ] || [ "$BUILD_NAME" == "GT-AX11000" ] || [ "$BUILD_NAME" == "GT-AXE11000" ] || [ "$BUILD_NAME" == "GT-AX6000" ] || [ "$BUILD_NAME" == "GT-AXE16000" ] || [ "$BUILD_NAME" == "GT-AX11000_PRO" ]
then
        cp -f release/src/router/aura_sw/prebuild/* $REPO/release/src/router/aura_sw/prebuild/$BUILD_NAME/
fi
if [ "$BUILD_NAME" == "RT-AX95Q" ] || [ "$BUILD_NAME" == "RT-AXE95Q" ]
then
    cp -a release/src/router/bluez-5.41/prebuild/* $REPO/release/src/router/bluez-5.41/prebuild/$BUILD_NAME/
fi


# Anything newer than SDK6
if [ "$SDK" != "" ]
then
	cp -f release/src/router/bsd/prebuilt/* $REPO/release/src/router/bsd/prebuilt/$BUILD_NAME/
	cp -f release/src/router/dhd/prebuilt/* $REPO/release/src/router/dhd/prebuilt/$BUILD_NAME/
fi

# Cleanup
rm $REPO/release/src/router/rc/prebuild/$BUILD_NAME/ate.o
rm $REPO/release/src/router/rc/prebuild/$BUILD_NAME/init-broadcom.o
rm $REPO/release/src/router/shared/prebuild/$BUILD_NAME/api-broadcom.o
