#!/bin/sh
sed -i 's/Arial, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/error_page.htm
sed -i 's/Arial, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/Main_Login.asp
sed -i 's/Arial, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/Main_Password.asp
sed -i 's/Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/css/asus_eula.css
sed -i 's/Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/form_style.css
sed -i 's/Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/sysdep/TUF-AX3000/www/css/asus_eula.css
sed -i 's/Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/sysdep/FUNCTION/ROG_UI/css/asus_eula.css
sed -i 's/Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Verdana, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/tmmenu.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/Advanced_WAN_Content.asp
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/app_installation.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/device-map/disk_utility.asp
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/form_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/NM_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/PrinterServer.asp
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/qis/qis_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/qis/QIS_finish.htm
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/sysdep/TUF-AX3000/www/form_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/sysdep/FUNCTION/ROG_UI/form_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/sysdep/GS-AX5400/www/index_style.css
sed -i 's/Arial, Helvetica, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Microsoft Yahei UI, Arial, Helvetica, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/tmmenu.css
sed -i 's/Courier, MS UI Gothic, MS P Gothic, Microsoft Yahei UI, sans-serif/Courier, Microsoft Yahei UI, MS UI Gothic, MS P Gothic, sans-serif/' release/src/router/www/form_style.css
