
version: 2.1


jobs:
  testbcm4912:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build bcm4912
          shell: /bin/bash
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/asuswrt-bcm bcm4912
            cd bcm4912/release/src-rt-5.04axhnd.675x
            sudo /home/docker/envs/bcm.sh
            make gt-ax6000
  testbcm675x:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build bcm675x
          shell: /bin/bash
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/asuswrt-bcm bcm675x
            cd bcm675x/release/src-rt-5.02axhnd.675x
            sudo /home/docker/envs/bcm.sh
            make rt-ax82u

  testbcm4908:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build bcm4908
          shell: /bin/bash
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/asuswrt-bcm bcm4908
            cd bcm4908/release/src-rt-5.02axhnd
            sudo /home/docker/envs/bcm.sh
            make gt-ax11000


workflows:
  build-workflow:
    jobs:
      - testbcm4912
      - testbcm675x
      - testbcm4908:
          requires:
            - testbcm675x


