#***********************************************************************
#
# Makefile
#
#***********************************************************************

include ../common.mak

all:
	cp -f linux/$(BUILD_NAME)/* linux/

install:
	@echo "do nothing."

.PHONY: clean
clean:
