name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo apt update
        sudo apt install libgtest-dev dnsperf
    - name: make
      run: |
        make all -j4
        make clean
    - name: test
      run: |
        make -C test test -j8
